/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light mode (default)
        surface: '#ffffff',
        'surface-dim': '#fafafa',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#f5f5f5',
        'surface-container-low': '#eeeeee',
        'surface-container': '#e9ecef',
        'surface-container-high': '#e0e0e0',
        'surface-container-highest': '#d4d4d4',
        'on-surface': '#090b0c',
        'on-surface-variant': '#6c757d',
        outline: '#737373',
        'outline-variant': '#cccccc',
        'surface-tint': '#d0d6d8',
        primary: '#0a7ea4',
        'on-primary': '#ffffff',
        'primary-container': '#b3e5fc',
        'on-primary-container': '#004d6d',
        'inverse-primary': '#4fc3f7',
        'primary-fixed': '#b3e5fc',
        'primary-fixed-dim': '#80deea',
        'on-primary-fixed': '#004d6d',
        'on-primary-fixed-variant': '#0277bd',
        secondary: '#5a9fb5',
        'on-secondary': '#ffffff',
        'secondary-container': '#b3dce8',
        'on-secondary-container': '#1a3a47',
        tertiary: '#7cb342',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c5e1a5',
        'on-tertiary-container': '#33600a',
        error: '#d32f2f',
        'on-error': '#ffffff',
        'error-container': '#ffcdd2',
        'on-error-container': '#b71c1c',
        background: '#ffffff',
        'on-background': '#090b0c',
        'surface-variant': '#e9ecef',
      },
      fontFamily: {
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.015em', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'unit': '8px',
        'sm': '12px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '24px',
      },
      borderRadius: {
        'full': '9999px',
        'lg': '8px',
        'default': '4px',
        'sm': '2px',
      },
      boxShadow: {
        'level-1': 'none',
        'level-2': '0 4px 12px rgba(0,0,0,0.1)',
        'level-3': '0 8px 24px rgba(0,0,0,0.12)',
        'focus': '0 0 0 3px rgba(10,126,164,0.1)',
      },
      transitionDuration: {
        'fast': '150ms',
        'base': '200ms',
        'slow': '300ms',
      },
      transitionTimingFunction: {
        'standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}